#! /bin/sh

DISTRIBUTION=Ubuntu-22.04

# Start Ubuntu 22.04
# Stop MSYS2 from mangling path names given at the command line by setting MSYS2_ARG_CONV_EXCL="*"
MSYS2_ARG_CONV_EXCL="*" wsl --cd ~ -d $DISTRIBUTION /usr/libexec/nslogin sudo -E -u $USERNAME bash -l

# Terminate Ubuntu 22.04
wsl -t $DISTRIBUTION
